config/routes.rb
Rails.application.routes.draw do
  get 'game', to: 'longest#game'

  get 'score', to: 'longest#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/longest_controller.rb
require 'longest_word.rb'

class LongestController < ApplicationController

  def game
    @grid_size = 10
    @grid = generate_grid(@grid_size)

  end

  def score
    @grid = params[:grid]
    @attempt = params[:attempt]
    @start_time = Time.parse(params[:start])
    @end_time = Time.now

    @answer = run_game(@attempt, @grid, @start_time, @end_time)
    # raise
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/longest_helper.rb
module LongestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/longest/game.html.erb
<h1>Longest#game</h1>


<%= init_grid = @grid %>

<br>
<br>
<br>

<%= start_time = Time.now %>

<br>

<form action="/score" method="get">
  <label for="question">What is your best attempt bro?</label>
  <input type="text" id="question" name="attempt" placeholder="type your attempt">
  <input type="hidden" name="start" value = '<%=start_time%>' >
  <input type="hidden" name="grid" value = '<%=init_grid%>' >
  <input type="submit" value="Go on!">

</form>

app/views/longest/score.html.erb
<h1>Longest#score</h1>


<div class="answer">You score is: <%= @answer[:score] %> and you word is: <%= @answer[:message] %> and translates into <%= @answer[:translation] %>
</div>
<br>

<%= link_to "play again", game_path %>